-- MySQL Script generated by MySQL Workbench
-- Wed Nov 27 16:50:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `usuario` ;

-- -----------------------------------------------------
-- Schema usuario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuario` DEFAULT CHARACTER SET utf8 ;
USE `usuario` ;

-- -----------------------------------------------------
-- Table `usuario`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario`.`usuario` ;

CREATE TABLE IF NOT EXISTS `usuario`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusuario_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `usuario`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `usuario`;
INSERT INTO `usuario`.`usuario` (`id`, `email`, `password`, `nombre`, `edad`) VALUES (DEFAULT, 'a@a.a', '1234', 'Aaaaa Aaaaa', 22);

COMMIT;

